openapi: 3.1.0
info:
  title: PECR API
  version: 1.0.0
  description: |
    Versioned API contract for PECR v1.
servers:
  - url: http://127.0.0.1:8080
    description: Gateway
  - url: http://127.0.0.1:8081
    description: Controller
paths:
  /healthz:
    get:
      summary: Liveness probe
      operationId: healthz
      responses:
        "200":
          description: Service process is running
          content:
            text/plain:
              schema:
                type: string
                const: ok
  /readyz:
    get:
      summary: Readiness probe
      operationId: readyz
      responses:
        "200":
          description: Service and dependencies are ready
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReadyzResponse"
        "503":
          description: One or more critical dependencies are unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReadyzResponse"
  /metrics:
    get:
      summary: Prometheus metrics
      operationId: metrics
      responses:
        "200":
          description: Metrics scrape
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Metrics rendering failed
  /v1/sessions:
    post:
      summary: Create policy-bound session
      operationId: createSession
      security:
        - PecrLocalPrincipal: []
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/XPecrRequestId"
        - $ref: "#/components/parameters/XPecrTraceId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [budget]
              properties:
                budget:
                  $ref: "#/components/schemas/Budget"
                as_of_time:
                  type: string
      responses:
        "200":
          description: Session created
          headers:
            x-pecr-session-token:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required: [session_id, trace_id, policy_snapshot_id, budget]
                properties:
                  session_id:
                    type: string
                  trace_id:
                    type: string
                  policy_snapshot_id:
                    type: string
                  budget:
                    $ref: "#/components/schemas/Budget"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing or invalid principal credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Denied by policy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: Source unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/operators/{op_name}:
    post:
      summary: Execute allowlisted operator
      operationId: callOperator
      security:
        - PecrSessionToken: []
          PecrLocalPrincipal: []
        - PecrSessionToken: []
          BearerAuth: []
      parameters:
        - name: op_name
          in: path
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/XPecrSessionToken"
        - $ref: "#/components/parameters/XPecrRequestId"
        - $ref: "#/components/parameters/XPecrTraceId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [session_id, params]
              properties:
                session_id:
                  type: string
                params:
                  type: object
      responses:
        "200":
          description: Operator executed
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required: [terminal_mode, result]
                properties:
                  terminal_mode:
                    $ref: "#/components/schemas/TerminalMode"
                  result:
                    type: object
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Denied by policy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: Budget exceeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Unknown session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Session already finalized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "501":
          description: Allowlisted operator not implemented
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "504":
          description: Policy engine timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: Source unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/finalize:
    post:
      summary: Finalize response with claim map gate
      operationId: finalize
      security:
        - PecrSessionToken: []
          PecrLocalPrincipal: []
        - PecrSessionToken: []
          BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/XPecrSessionToken"
        - $ref: "#/components/parameters/XPecrRequestId"
        - $ref: "#/components/parameters/XPecrTraceId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [session_id, response_text, claim_map]
              properties:
                session_id:
                  type: string
                response_text:
                  type: string
                claim_map:
                  $ref: "#/components/schemas/ClaimMap"
      responses:
        "200":
          description: Finalized
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required: [terminal_mode, trace_id, claim_map, response_text]
                properties:
                  terminal_mode:
                    $ref: "#/components/schemas/TerminalMode"
                  trace_id:
                    type: string
                  claim_map:
                    $ref: "#/components/schemas/ClaimMap"
                  response_text:
                    type: string
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Denied by policy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Unknown session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Session already finalized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "504":
          description: Policy engine timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: Source unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/run:
    post:
      summary: Controller end-to-end run
      operationId: run
      security:
        - PecrLocalPrincipal: []
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/XPecrRequestId"
        - $ref: "#/components/parameters/XPecrTraceId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [query]
              properties:
                query:
                  type: string
                budget:
                  $ref: "#/components/schemas/Budget"
      responses:
        "200":
          description: Finalized response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required: [terminal_mode, trace_id, claim_map, response_text]
                properties:
                  terminal_mode:
                    $ref: "#/components/schemas/TerminalMode"
                  trace_id:
                    type: string
                  claim_map:
                    $ref: "#/components/schemas/ClaimMap"
                  response_text:
                    type: string
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Missing or invalid principal credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal controller failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "503":
          description: Authentication subsystem unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "502":
          description: Gateway/source unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    PecrLocalPrincipal:
      type: apiKey
      in: header
      name: x-pecr-principal-id
      description: Local mode principal identity header (`PECR_AUTH_MODE=local`).
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OIDC bearer token (`PECR_AUTH_MODE=oidc`).
    PecrSessionToken:
      type: apiKey
      in: header
      name: x-pecr-session-token
      description: Opaque session capability token returned from `POST /v1/sessions`.
  parameters:
    XPecrSessionToken:
      name: x-pecr-session-token
      in: header
      required: true
      schema:
        type: string
      description: Required for `/v1/operators/{op_name}` and `/v1/finalize`.
    XPecrRequestId:
      name: x-pecr-request-id
      in: header
      required: false
      schema:
        type: string
      description: Optional caller-provided id used for log correlation.
    XPecrTraceId:
      name: x-pecr-trace-id
      in: header
      required: false
      schema:
        type: string
      description: Optional trace id propagated across controller and gateway.
  schemas:
    ReadyzResponse:
      type: object
      additionalProperties: false
      required: [status, checks]
      properties:
        status:
          type: string
          enum: [ready, not_ready]
        checks:
          type: object
          additionalProperties:
            type: boolean
    Budget:
      type: object
      additionalProperties: false
      required:
        - max_operator_calls
        - max_bytes
        - max_wallclock_ms
        - max_recursion_depth
      properties:
        max_operator_calls:
          type: integer
          minimum: 0
          maximum: 10000
        max_bytes:
          type: integer
          minimum: 0
          maximum: 67108864
        max_wallclock_ms:
          type: integer
          minimum: 0
          maximum: 300000
        max_recursion_depth:
          type: integer
          minimum: 0
          maximum: 20
        max_parallelism:
          type: integer
          minimum: 1
          maximum: 256
          description: Maximum concurrent operator calls for controller fan-out steps (baseline `search_ref_fetch_span` and RLM batch bridge calls). Defaults to 1 when omitted.
    TerminalMode:
      type: string
      enum:
        - SUPPORTED
        - INSUFFICIENT_EVIDENCE
        - INSUFFICIENT_PERMISSION
        - SOURCE_UNAVAILABLE
    Claim:
      type: object
      additionalProperties: false
      required:
        - claim_id
        - claim_text
        - status
        - evidence_unit_ids
      properties:
        claim_id:
          type: string
          pattern: "^[a-f0-9]{64}$"
        claim_text:
          type: string
          minLength: 1
        status:
          type: string
          enum:
            - SUPPORTED
            - ASSUMPTION
            - UNKNOWN
        evidence_unit_ids:
          type: array
          items:
            type: string
            pattern: "^[a-f0-9]{64}$"
    ClaimMap:
      type: object
      additionalProperties: false
      required:
        - claim_map_id
        - terminal_mode
        - claims
        - coverage_threshold
        - coverage_observed
      properties:
        claim_map_id:
          type: string
        terminal_mode:
          $ref: "#/components/schemas/TerminalMode"
        claims:
          type: array
          items:
            $ref: "#/components/schemas/Claim"
        coverage_threshold:
          type: number
          minimum: 0
          maximum: 1
        coverage_observed:
          type: number
          minimum: 0
          maximum: 1
        notes:
          type: string
    ErrorResponse:
      type: object
      additionalProperties: false
      required:
        - code
        - message
        - terminal_mode_hint
        - retryable
      properties:
        code:
          type: string
          minLength: 1
        message:
          type: string
          minLength: 1
        terminal_mode_hint:
          $ref: "#/components/schemas/TerminalMode"
        retryable:
          type: boolean
        detail:
          oneOf:
            - type: object
            - type: array
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: null
